# Generated by Django 4.1 on 2022-08-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carino.car')),
            ],
        ),
    ]
