# Generated by Django 4.1 on 2022-08-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carino', '0003_alter_carchoice_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carchoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='carchoice',
            name='car_model',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
